import React from "react";
import "./styles.css";
import "./forest.css";
import "./mud.css";

export default function App() {
  return (
    <div className="App">
      <div className="plant"></div>

      <div className="background-forest">
        <div className="base-forest">
          <div id="light-1" className="circle"></div>
          <div id="light-2" className="circle"></div>
          <div id="light-3" className="circle"></div>
          <div id="light-4" className="circle"></div>
          <div id="light-5" className="circle"></div>
          <div id="light-6" className="circle"></div>
          <div id="light-7" className="circle"></div>
          <div id="light-8" className="circle"></div>
          <div id="light-9" className="circle"></div>
          <div id="light-10" className="circle"></div>
          <div id="light-11" className="circle"></div>
          <div id="light-12" className="circle"></div>
          <div id="light-13" className="circle"></div>
          <div id="light-14" className="circle"></div>
          <div id="light-15" className="circle"></div>
          <div id="light-16" className="circle"></div>
          <div id="light-17" className="circle"></div>
          <div id="light-18" className="circle"></div>
          <div id="light-19" className="circle"></div>
          <div id="light-20" className="circle"></div>
          <div id="light-21" className="circle"></div>
          <div id="light-22" className="circle"></div>
          <div id="light-23" className="circle"></div>
          <div id="light-24" className="circle"></div>
          <div id="light-25" className="circle"></div>
          <div id="light-26" className="circle"></div>
          <div id="light-27" className="circle"></div>
          <div id="light-28" className="circle"></div>
          <div id="light-29" className="circle"></div>
          <div id="light-30" className="circle"></div>
          <div id="light-31" className="circle"></div>
          <div id="light-32" className="circle"></div>
          <div id="light-33" className="circle"></div>
          <div id="light-34" className="circle"></div>
          <div id="light-35" className="circle"></div>
          <div id="light-36" className="circle"></div>
          <div id="light-37" className="circle"></div>
          <div id="light-38" className="circle"></div>
          <div id="light-39" className="circle"></div>
          <div id="light-40" className="circle"></div>
          <div id="light-41" className="circle"></div>
          <div id="light-42" className="circle"></div>
          <div id="light-43" className="circle"></div>
          <div id="light-44" className="circle"></div>
          <div id="light-45" className="circle"></div>
          <div id="light-46" className="circle"></div>
          <div id="light-47" className="circle"></div>
          <div id="light-48" className="circle"></div>
          <div id="light-49" className="circle"></div>
          <div id="light-50" className="circle"></div>
          <div id="light-51" className="circle"></div>
          <div id="light-52" className="circle"></div>
          <div id="light-53" className="circle"></div>
          <div id="light-54" className="circle"></div>
          <div id="light-55" className="circle"></div>
          <div id="light-56" className="circle"></div>
          <div id="light-57" className="circle"></div>
          <div id="light-58" className="circle"></div>
          <div id="light-59" className="circle"></div>
          <div id="light-60" className="circle"></div>
          <div id="light-61" className="circle"></div>
          <div id="light-62" className="circle"></div>
          <div id="light-63" className="circle"></div>
          <div id="light-64" className="circle"></div>
          <div id="light-65" className="circle"></div>
          <div id="light-66" className="circle"></div>
          <div id="light-67" className="circle"></div>
          <div id="light-68" className="circle"></div>
          <div id="light-69" className="circle"></div>
          <div id="light-70" className="circle"></div>
          <div id="light-71" className="circle"></div>
          <div id="light-72" className="circle"></div>
          <div id="light-73" className="circle"></div>
          <div id="light-74" className="circle"></div>
          <div id="light-75" className="circle"></div>
          <div id="light-76" className="circle"></div>
          <div id="light-77" className="circle"></div>
          <div id="light-78" className="circle"></div>
          <div id="light-79" className="circle"></div>
          <div id="light-80" className="circle"></div>
          <div id="light-81" className="circle"></div>
          <div id="light-82" className="circle"></div>
          <div id="light-83" className="circle"></div>
          <div id="light-84" className="circle"></div>
          <div id="light-85" className="circle"></div>
          <div id="light-86" className="circle"></div>
          <div id="light-87" className="circle"></div>
          <div id="light-88" className="circle"></div>
          <div id="light-89" className="circle"></div>
          <div id="light-90" className="circle"></div>
          <div id="light-91" className="circle"></div>
          <div id="light-92" className="circle"></div>
          <div id="light-93" className="circle"></div>
          <div id="light-94" className="circle"></div>
          <div id="light-95" className="circle"></div>
          <div id="light-96" className="circle"></div>
          <div id="light-97" className="circle"></div>
          <div id="light-98" className="circle"></div>
          <div id="light-99" className="circle"></div>
          <div id="light-100" className="circle"></div>
          <div id="light-101" className="circle"></div>
          <div id="light-102" className="circle"></div>
          <div id="light-103" className="circle"></div>
          <div id="light-104" className="circle"></div>
          <div id="light-105" className="circle"></div>
          <div id="light-106" className="circle"></div>
          <div id="light-107" className="circle"></div>
          <div id="light-108" className="circle"></div>
          <div id="light-109" className="circle"></div>
          <div id="light-110" className="circle"></div>
          <div id="light-111" className="circle"></div>
          <div id="light-112" className="circle"></div>
          <div id="light-113" className="circle"></div>
          <div id="light-114" className="circle"></div>
          <div id="light-115" className="circle"></div>
          <div id="light-116" className="circle"></div>
          <div id="light-117" className="circle"></div>
          <div id="light-118" className="circle"></div>
          <div id="light-119" className="circle"></div>
          <div id="light-120" className="circle"></div>
          <div id="light-121" className="circle"></div>
          <div id="light-122" className="circle"></div>
          <div id="light-123" className="circle"></div>
          <div id="light-124" className="circle"></div>
          <div id="light-125" className="circle"></div>
          <div id="light-126" className="circle"></div>
          <div id="light-127" className="circle"></div>
          <div id="light-128" className="circle"></div>
          <div id="light-129" className="circle"></div>
          <div id="light-130" className="circle"></div>
          <div id="light-131" className="circle"></div>
          <div id="light-132" className="circle"></div>
          <div id="light-133" className="circle"></div>
          <div id="light-134" className="circle"></div>
          <div id="light-135" className="circle"></div>
          <div id="light-136" className="circle"></div>
          <div id="light-137" className="circle"></div>
          <div id="light-138" className="circle"></div>
          <div id="light-139" className="circle"></div>
          <div id="light-140" className="circle"></div>
          <div id="light-141" className="circle"></div>
          <div id="light-142" className="circle"></div>
          <div id="light-143" className="circle"></div>
          <div id="light-144" className="circle"></div>
          <div id="light-145" className="circle"></div>
          <div id="light-146" className="circle"></div>
          <div id="light-147" className="circle"></div>
          <div id="light-148" className="circle"></div>
          <div id="light-149" className="circle"></div>
          <div id="light-150" className="circle"></div>
          <div id="light-151" className="circle"></div>
          <div id="light-152" className="circle"></div>
          <div id="light-153" className="circle"></div>
          <div id="light-154" className="circle"></div>
          <div id="light-155" className="circle"></div>
          <div id="light-156" className="circle"></div>
          <div id="light-157" className="circle"></div>
          <div id="light-158" className="circle"></div>
          <div id="light-159" className="circle"></div>
          <div id="light-160" className="circle"></div>
          <div id="light-161" className="circle"></div>
          <div id="light-162" className="circle"></div>
          <div id="light-163" className="circle"></div>
          <div id="light-164" className="circle"></div>
          <div id="light-165" className="circle"></div>
          <div id="light-166" className="circle"></div>
          <div id="light-167" className="circle"></div>
          <div id="light-168" className="circle"></div>
          <div id="light-169" className="circle"></div>
          <div id="light-170" className="circle"></div>
          <div id="light-171" className="circle"></div>
          <div id="light-172" className="circle"></div>
          <div id="light-173" className="circle"></div>
          <div id="light-174" className="circle"></div>
          <div id="light-175" className="circle"></div>
          <div id="light-176" className="circle"></div>
          <div id="light-177" className="circle"></div>
          <div id="light-178" className="circle"></div>
          <div id="light-179" className="circle"></div>
          <div id="light-180" className="circle"></div>
          <div id="light-181" className="circle"></div>
          <div id="light-182" className="circle"></div>
          <div id="light-183" className="circle"></div>
          <div id="light-184" className="circle"></div>
          <div id="light-185" className="circle"></div>
          <div id="light-186" className="circle"></div>
          <div id="light-187" className="circle"></div>
          <div id="light-188" className="circle"></div>
          <div id="light-189" className="circle"></div>
          <div id="light-190" className="circle"></div>
          <div id="light-191" className="circle"></div>
          <div id="light-192" className="circle"></div>
          <div id="light-193" className="circle"></div>
          <div id="light-194" className="circle"></div>
          <div id="light-195" className="circle"></div>
          <div id="light-196" className="circle"></div>
          <div id="light-197" className="circle"></div>
          <div id="light-198" className="circle"></div>
          <div id="light-199" className="circle"></div>
          <div id="light-200" className="circle"></div>
          <div id="light-201" className="circle"></div>
          <div id="light-202" className="circle"></div>
          <div id="light-203" className="circle"></div>
          <div id="light-204" className="circle"></div>
          <div id="light-205" className="circle"></div>
          <div id="light-206" className="circle"></div>
          <div id="light-207" className="circle"></div>
          <div id="light-208" className="circle"></div>
          <div id="light-209" className="circle"></div>
          <div id="light-210" className="circle"></div>
          <div id="light-211" className="circle"></div>
          <div id="light-212" className="circle"></div>
          <div id="light-213" className="circle"></div>
          <div id="light-214" className="circle"></div>
          <div id="light-215" className="circle"></div>
          <div id="light-216" className="circle"></div>
          <div id="light-217" className="circle"></div>
          <div id="light-218" className="circle"></div>
          <div id="light-219" className="circle"></div>
          <div id="light-220" className="circle"></div>
          <div id="light-221" className="circle"></div>
          <div id="light-222" className="circle"></div>
          <div id="light-223" className="circle"></div>
          <div id="light-224" className="circle"></div>
          <div id="light-225" className="circle"></div>
          <div id="light-226" className="circle"></div>
          <div id="light-227" className="circle"></div>
          <div id="light-228" className="circle"></div>
          <div id="light-229" className="circle"></div>
          <div id="light-230" className="circle"></div>
          <div id="light-231" className="circle"></div>
          <div id="light-232" className="circle"></div>
          <div id="light-233" className="circle"></div>
          <div id="light-234" className="circle"></div>
          <div id="light-235" className="circle"></div>
          <div id="light-236" className="circle"></div>
          <div id="light-237" className="circle"></div>
          <div id="light-238" className="circle"></div>
          <div id="light-239" className="circle"></div>
          <div id="light-240" className="circle"></div>
          <div id="light-241" className="circle"></div>
          <div id="light-242" className="circle"></div>
          <div id="light-243" className="circle"></div>
          <div id="light-244" className="circle"></div>
          <div id="light-245" className="circle"></div>
          <div id="light-246" className="circle"></div>
          <div id="light-247" className="circle"></div>
          <div id="light-248" className="circle"></div>
          <div id="light-249" className="circle"></div>
          <div id="light-250" className="circle"></div>
          <div id="light-251" className="circle"></div>
          <div id="light-252" className="circle"></div>
          <div id="light-253" className="circle"></div>
          <div id="light-254" className="circle"></div>
          <div id="light-255" className="circle"></div>
          <div id="light-256" className="circle"></div>
          <div id="light-257" className="circle"></div>
          <div id="light-258" className="circle"></div>
          <div id="light-259" className="circle"></div>
          <div id="light-260" className="circle"></div>
          <div id="light-261" className="circle"></div>
          <div id="light-262" className="circle"></div>
          <div id="light-263" className="circle"></div>
          <div id="light-264" className="circle"></div>
          <div id="light-265" className="circle"></div>
          <div id="light-266" className="circle"></div>
          <div id="light-267" className="circle"></div>
          <div id="light-268" className="circle"></div>
          <div id="light-269" className="circle"></div>
          <div id="light-270" className="circle"></div>
          <div id="light-271" className="circle"></div>
          <div id="light-272" className="circle"></div>
          <div id="light-273" className="circle"></div>
          <div id="light-274" className="circle"></div>
          <div id="light-275" className="circle"></div>
          <div id="light-276" className="circle"></div>
          <div id="light-277" className="circle"></div>
          <div id="light-278" className="circle"></div>
          <div id="light-279" className="circle"></div>
          <div id="light-280" className="circle"></div>
          <div id="light-281" className="circle"></div>
          <div id="light-282" className="circle"></div>
          <div id="light-283" className="circle"></div>
          <div id="light-284" className="circle"></div>
          <div id="light-285" className="circle"></div>
          <div id="light-286" className="circle"></div>
          <div id="light-287" className="circle"></div>
          <div id="light-288" className="circle"></div>
          <div id="light-289" className="circle"></div>
          <div id="light-290" className="circle"></div>
          <div id="light-291" className="circle"></div>
          <div id="light-292" className="circle"></div>
          <div id="light-293" className="circle"></div>
          <div id="light-294" className="circle"></div>
          <div id="light-295" className="circle"></div>
          <div id="light-296" className="circle"></div>
          <div id="light-297" className="circle"></div>
          <div id="light-298" className="circle"></div>
          <div id="light-299" className="circle"></div>
          <div id="light-300" className="circle"></div>
        </div>
      </div>

      <div className="background-mud">
        <div className="base-mud">
          <div id="light-1" className="circle"></div>
          <div id="light-2" className="circle"></div>
          <div id="light-3" className="circle"></div>
          <div id="light-4" className="circle"></div>
          <div id="light-5" className="circle"></div>
          <div id="light-6" className="circle"></div>
          <div id="light-7" className="circle"></div>
          <div id="light-8" className="circle"></div>
          <div id="light-9" className="circle"></div>
          <div id="light-10" className="circle"></div>
          <div id="light-11" className="circle"></div>
          <div id="light-12" className="circle"></div>
          <div id="light-13" className="circle"></div>
          <div id="light-14" className="circle"></div>
          <div id="light-15" className="circle"></div>
          <div id="light-16" className="circle"></div>
          <div id="light-17" className="circle"></div>
          <div id="light-18" className="circle"></div>
          <div id="light-19" className="circle"></div>
          <div id="light-20" className="circle"></div>
          <div id="light-21" className="circle"></div>
          <div id="light-22" className="circle"></div>
          <div id="light-23" className="circle"></div>
          <div id="light-24" className="circle"></div>
          <div id="light-25" className="circle"></div>
          <div id="light-26" className="circle"></div>
          <div id="light-27" className="circle"></div>
          <div id="light-28" className="circle"></div>
          <div id="light-29" className="circle"></div>
          <div id="light-30" className="circle"></div>
          <div id="light-31" className="circle"></div>
          <div id="light-32" className="circle"></div>
          <div id="light-33" className="circle"></div>
          <div id="light-34" className="circle"></div>
          <div id="light-35" className="circle"></div>
          <div id="light-36" className="circle"></div>
          <div id="light-37" className="circle"></div>
          <div id="light-38" className="circle"></div>
          <div id="light-39" className="circle"></div>
          <div id="light-40" className="circle"></div>
          <div id="light-41" className="circle"></div>
          <div id="light-42" className="circle"></div>
          <div id="light-43" className="circle"></div>
          <div id="light-44" className="circle"></div>
          <div id="light-45" className="circle"></div>
          <div id="light-46" className="circle"></div>
          <div id="light-47" className="circle"></div>
          <div id="light-48" className="circle"></div>
          <div id="light-49" className="circle"></div>
          <div id="light-50" className="circle"></div>
          <div id="light-51" className="circle"></div>
          <div id="light-52" className="circle"></div>
          <div id="light-53" className="circle"></div>
          <div id="light-54" className="circle"></div>
          <div id="light-55" className="circle"></div>
          <div id="light-56" className="circle"></div>
          <div id="light-57" className="circle"></div>
          <div id="light-58" className="circle"></div>
          <div id="light-59" className="circle"></div>
          <div id="light-60" className="circle"></div>
          <div id="light-61" className="circle"></div>
          <div id="light-62" className="circle"></div>
          <div id="light-63" className="circle"></div>
          <div id="light-64" className="circle"></div>
          <div id="light-65" className="circle"></div>
          <div id="light-66" className="circle"></div>
          <div id="light-67" className="circle"></div>
          <div id="light-68" className="circle"></div>
          <div id="light-69" className="circle"></div>
          <div id="light-70" className="circle"></div>
          <div id="light-71" className="circle"></div>
          <div id="light-72" className="circle"></div>
          <div id="light-73" className="circle"></div>
          <div id="light-74" className="circle"></div>
          <div id="light-75" className="circle"></div>
          <div id="light-76" className="circle"></div>
          <div id="light-77" className="circle"></div>
          <div id="light-78" className="circle"></div>
          <div id="light-79" className="circle"></div>
          <div id="light-80" className="circle"></div>
          <div id="light-81" className="circle"></div>
          <div id="light-82" className="circle"></div>
          <div id="light-83" className="circle"></div>
          <div id="light-84" className="circle"></div>
          <div id="light-85" className="circle"></div>
          <div id="light-86" className="circle"></div>
          <div id="light-87" className="circle"></div>
          <div id="light-88" className="circle"></div>
          <div id="light-89" className="circle"></div>
          <div id="light-90" className="circle"></div>
          <div id="light-91" className="circle"></div>
          <div id="light-92" className="circle"></div>
          <div id="light-93" className="circle"></div>
          <div id="light-94" className="circle"></div>
          <div id="light-95" className="circle"></div>
          <div id="light-96" className="circle"></div>
          <div id="light-97" className="circle"></div>
          <div id="light-98" className="circle"></div>
          <div id="light-99" className="circle"></div>
          <div id="light-100" className="circle"></div>
          <div id="light-101" className="circle"></div>
          <div id="light-102" className="circle"></div>
          <div id="light-103" className="circle"></div>
          <div id="light-104" className="circle"></div>
          <div id="light-105" className="circle"></div>
          <div id="light-106" className="circle"></div>
          <div id="light-107" className="circle"></div>
          <div id="light-108" className="circle"></div>
          <div id="light-109" className="circle"></div>
          <div id="light-110" className="circle"></div>
          <div id="light-111" className="circle"></div>
          <div id="light-112" className="circle"></div>
          <div id="light-113" className="circle"></div>
          <div id="light-114" className="circle"></div>
          <div id="light-115" className="circle"></div>
          <div id="light-116" className="circle"></div>
          <div id="light-117" className="circle"></div>
          <div id="light-118" className="circle"></div>
          <div id="light-119" className="circle"></div>
          <div id="light-120" className="circle"></div>
          <div id="light-121" className="circle"></div>
          <div id="light-122" className="circle"></div>
          <div id="light-123" className="circle"></div>
          <div id="light-124" className="circle"></div>
          <div id="light-125" className="circle"></div>
          <div id="light-126" className="circle"></div>
          <div id="light-127" className="circle"></div>
          <div id="light-128" className="circle"></div>
          <div id="light-129" className="circle"></div>
          <div id="light-130" className="circle"></div>
          <div id="light-131" className="circle"></div>
          <div id="light-132" className="circle"></div>
          <div id="light-133" className="circle"></div>
          <div id="light-134" className="circle"></div>
          <div id="light-135" className="circle"></div>
          <div id="light-136" className="circle"></div>
          <div id="light-137" className="circle"></div>
          <div id="light-138" className="circle"></div>
          <div id="light-139" className="circle"></div>
          <div id="light-140" className="circle"></div>
          <div id="light-141" className="circle"></div>
          <div id="light-142" className="circle"></div>
          <div id="light-143" className="circle"></div>
          <div id="light-144" className="circle"></div>
          <div id="light-145" className="circle"></div>
          <div id="light-146" className="circle"></div>
          <div id="light-147" className="circle"></div>
          <div id="light-148" className="circle"></div>
          <div id="light-149" className="circle"></div>
          <div id="light-150" className="circle"></div>
          <div id="light-151" className="circle"></div>
          <div id="light-152" className="circle"></div>
          <div id="light-153" className="circle"></div>
          <div id="light-154" className="circle"></div>
          <div id="light-155" className="circle"></div>
          <div id="light-156" className="circle"></div>
          <div id="light-157" className="circle"></div>
          <div id="light-158" className="circle"></div>
          <div id="light-159" className="circle"></div>
          <div id="light-160" className="circle"></div>
          <div id="light-161" className="circle"></div>
          <div id="light-162" className="circle"></div>
          <div id="light-163" className="circle"></div>
          <div id="light-164" className="circle"></div>
          <div id="light-165" className="circle"></div>
          <div id="light-166" className="circle"></div>
          <div id="light-167" className="circle"></div>
          <div id="light-168" className="circle"></div>
          <div id="light-169" className="circle"></div>
          <div id="light-170" className="circle"></div>
          <div id="light-171" className="circle"></div>
          <div id="light-172" className="circle"></div>
          <div id="light-173" className="circle"></div>
          <div id="light-174" className="circle"></div>
          <div id="light-175" className="circle"></div>
          <div id="light-176" className="circle"></div>
          <div id="light-177" className="circle"></div>
          <div id="light-178" className="circle"></div>
          <div id="light-179" className="circle"></div>
          <div id="light-180" className="circle"></div>
          <div id="light-181" className="circle"></div>
          <div id="light-182" className="circle"></div>
          <div id="light-183" className="circle"></div>
          <div id="light-184" className="circle"></div>
          <div id="light-185" className="circle"></div>
          <div id="light-186" className="circle"></div>
          <div id="light-187" className="circle"></div>
          <div id="light-188" className="circle"></div>
          <div id="light-189" className="circle"></div>
          <div id="light-190" className="circle"></div>
          <div id="light-191" className="circle"></div>
          <div id="light-192" className="circle"></div>
          <div id="light-193" className="circle"></div>
          <div id="light-194" className="circle"></div>
          <div id="light-195" className="circle"></div>
          <div id="light-196" className="circle"></div>
          <div id="light-197" className="circle"></div>
          <div id="light-198" className="circle"></div>
          <div id="light-199" className="circle"></div>
          <div id="light-200" className="circle"></div>
          <div id="light-201" className="circle"></div>
          <div id="light-202" className="circle"></div>
          <div id="light-203" className="circle"></div>
          <div id="light-204" className="circle"></div>
          <div id="light-205" className="circle"></div>
          <div id="light-206" className="circle"></div>
          <div id="light-207" className="circle"></div>
          <div id="light-208" className="circle"></div>
          <div id="light-209" className="circle"></div>
          <div id="light-210" className="circle"></div>
          <div id="light-211" className="circle"></div>
          <div id="light-212" className="circle"></div>
          <div id="light-213" className="circle"></div>
          <div id="light-214" className="circle"></div>
          <div id="light-215" className="circle"></div>
          <div id="light-216" className="circle"></div>
          <div id="light-217" className="circle"></div>
          <div id="light-218" className="circle"></div>
          <div id="light-219" className="circle"></div>
          <div id="light-220" className="circle"></div>
          <div id="light-221" className="circle"></div>
          <div id="light-222" className="circle"></div>
          <div id="light-223" className="circle"></div>
          <div id="light-224" className="circle"></div>
          <div id="light-225" className="circle"></div>
          <div id="light-226" className="circle"></div>
          <div id="light-227" className="circle"></div>
          <div id="light-228" className="circle"></div>
          <div id="light-229" className="circle"></div>
          <div id="light-230" className="circle"></div>
          <div id="light-231" className="circle"></div>
          <div id="light-232" className="circle"></div>
          <div id="light-233" className="circle"></div>
          <div id="light-234" className="circle"></div>
          <div id="light-235" className="circle"></div>
          <div id="light-236" className="circle"></div>
          <div id="light-237" className="circle"></div>
          <div id="light-238" className="circle"></div>
          <div id="light-239" className="circle"></div>
          <div id="light-240" className="circle"></div>
          <div id="light-241" className="circle"></div>
          <div id="light-242" className="circle"></div>
          <div id="light-243" className="circle"></div>
          <div id="light-244" className="circle"></div>
          <div id="light-245" className="circle"></div>
          <div id="light-246" className="circle"></div>
          <div id="light-247" className="circle"></div>
          <div id="light-248" className="circle"></div>
          <div id="light-249" className="circle"></div>
          <div id="light-250" className="circle"></div>
          <div id="light-251" className="circle"></div>
          <div id="light-252" className="circle"></div>
          <div id="light-253" className="circle"></div>
          <div id="light-254" className="circle"></div>
          <div id="light-255" className="circle"></div>
          <div id="light-256" className="circle"></div>
          <div id="light-257" className="circle"></div>
          <div id="light-258" className="circle"></div>
          <div id="light-259" className="circle"></div>
          <div id="light-260" className="circle"></div>
          <div id="light-261" className="circle"></div>
          <div id="light-262" className="circle"></div>
          <div id="light-263" className="circle"></div>
          <div id="light-264" className="circle"></div>
          <div id="light-265" className="circle"></div>
          <div id="light-266" className="circle"></div>
          <div id="light-267" className="circle"></div>
          <div id="light-268" className="circle"></div>
          <div id="light-269" className="circle"></div>
          <div id="light-270" className="circle"></div>
          <div id="light-271" className="circle"></div>
          <div id="light-272" className="circle"></div>
          <div id="light-273" className="circle"></div>
          <div id="light-274" className="circle"></div>
          <div id="light-275" className="circle"></div>
          <div id="light-276" className="circle"></div>
          <div id="light-277" className="circle"></div>
          <div id="light-278" className="circle"></div>
          <div id="light-279" className="circle"></div>
          <div id="light-280" className="circle"></div>
          <div id="light-281" className="circle"></div>
          <div id="light-282" className="circle"></div>
          <div id="light-283" className="circle"></div>
          <div id="light-284" className="circle"></div>
          <div id="light-285" className="circle"></div>
          <div id="light-286" className="circle"></div>
          <div id="light-287" className="circle"></div>
          <div id="light-288" className="circle"></div>
          <div id="light-289" className="circle"></div>
          <div id="light-290" className="circle"></div>
          <div id="light-291" className="circle"></div>
          <div id="light-292" className="circle"></div>
          <div id="light-293" className="circle"></div>
          <div id="light-294" className="circle"></div>
          <div id="light-295" className="circle"></div>
          <div id="light-296" className="circle"></div>
          <div id="light-297" className="circle"></div>
          <div id="light-298" className="circle"></div>
          <div id="light-299" className="circle"></div>
          <div id="light-300" className="circle"></div>
        </div>
      </div>
    </div>
  );
}
